name: lit-review
channels:
  - conda-forge
dependencies:
  - pybliometrics
  - ipykernel
  - yaml
  - pandas
  - bibtexparser
  - pybtex
  - graphviz
  - seaborn
  - squarify
  - openpyxl
  - kaleido
  - plotly
  - pip:
    - python-dotenv
    - wos
    - snakemake
